services:
  mysql-service-1:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '141198'
      MYSQL_DATABASE: 'reservas_auth'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: '141198'
    ports:
      - '3307:3306'
    #volumes:
     # - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent"]
      interval: 30s
      timeout: 10s
      retries: 5


  mysql-service-2:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '141198'
      MYSQL_DATABASE: 'reservas_services'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: '141198'
    ports:
      - '3308:3306'
      #volumes:
      # - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent" ]
      interval: 30s
      timeout: 10s
      retries: 5
  mysql-service-3:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '141198'
      MYSQL_DATABASE: 'reservas_resevartionsHistory'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: '141198'
    ports:
      - '3309:3306'
      #volumes:
      # - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent" ]
      interval: 30s
      timeout: 10s
      retries: 5
    mysql-service-4:
      image: 'mysql:latest'
      environment:
        MYSQL_ROOT_PASSWORD: '141198'
        MYSQL_DATABASE: 'reservas_users'
        MYSQL_USER: 'mysqluser'
        MYSQL_PASSWORD: '141198'
      ports:
        - '3310:3306'
        #volumes:
        # - mysql_data:/var/lib/mysql
      networks:
        - app-network
      healthcheck:
        test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent" ]
        interval: 30s
        timeout: 10s
        retries: 5
    mysql-service-5:
      image: 'mysql:latest'
      environment:
        MYSQL_ROOT_PASSWORD: '141198'
        MYSQL_DATABASE: 'reservas_notes'
        MYSQL_USER: 'mysqluser'
        MYSQL_PASSWORD: '141198'
      ports:
        - '3312:3306'
        #volumes:
        # - mysql_data:/var/lib/mysql
      networks:
        - app-network
      healthcheck:
        test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent" ]
        interval: 30s
        timeout: 10s
        retries: 5
  mysql-service-6:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '141198'
      MYSQL_DATABASE: 'reservas_resevartions'
      MYSQL_USER: 'mysqluser'
      MYSQL_PASSWORD: '141198'
    ports:
      - '3313:3306'
      #volumes:
      # - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p141198 --silent" ]
      interval: 30s
      timeout: 10s
      retries: 5
#volumes:
 # mysql_data:

networks:
  app-network: