server:
  port: 8080

spring:
  config:
   import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: auth
        uri: http://localhost:8095
        predicates:
        - Path=/auth/**
        - Path=/api/**
      - id: reviews
        uri: http://localhost:8099
        predicates:
        - Path=/api/review/**
      - id: Reservaciones
        uri: http://localhost:8065
        predicates:
        - Path=/api/reservation/**
      - id: Services
        uri: http://localhost:8060
        predicates:
        - Path=/api/services/**
        - Path=/api/categories/**
      - id: UserServices
        uri: http://localhost:8072
        predicates:
        - Path=/api/users/**
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
       
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    sql: debug
 
  
  