server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: authautenticacion-service
        uri: http://localhost:8095
        predicates:
        - Path=/auth/**  /api/**
        filters:
            - RewritePath=/api/(?<path>.*), /${path}
      - id: reviews
        uri: http://localhost:8099
        predicates:
        - Path=/api/review/**
      - id: Reservaciones
        uri: http://localhost:8065
        predicates:
        - Path=/api/reservation/**
      - id: services
        uri: http://localhost:8060
        predicates:
        - Path=/api/services/** /api/categories/**
      - id: userServices
        uri: http://localhost:8072
        predicates:
        - Path=/api/users/**

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: false


 
  
  