server:
  port: 8060

spring:
  application:
    name: Services
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reservasgestionservices?useSSL=false&serverTimezone=UTCC&allowPublicKeyRetrieval=true
    username: mysqluser
    password: 141198
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8888
  security:
    jwt:
      key:
        private: D130eU2ffROd+8QcHSLHzUURp4Bsy8DHSmrh8I/BDqQ
      user:
        generator: ANG_KEY
file:
  upload-dir: upload


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    sql: debug
