 name: Deploy Microservices

 on:
  push:
    branches:
      - main

 jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker images
        run: |
          docker buildx build --push --tag myapp/user-service:latest ./user-service
          docker buildx build --push --tag myapp/service-service:latest ./service-service
          docker buildx build --push --tag myapp/reservation-service:latest ./reservation-service
          docker buildx build --push --tag myapp/notes-service:latest ./notes-service

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
